sudo: required
services:
  - docker

before_install:
  - docker build -t federicoyre/react-test-complex -f ./client/Dockerfile.dev ./client

script: 
  - docker run federicoyre/react-test-complex npm test -- --coverage

after_success:
  - docker build -t federicoyre/complex-client ./client
  - docker build -t federicoyre/complex-nginx ./nginx
  - docker build -t federicoyre/complex-server ./server
  - docker build -t federicoyre/complex-worker ./worker
  # Log in to docker CLI from ENV variables
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push federicoyre/complex-client
  - docker push federicoyre/complex-nginx
  - docker push federicoyre/complex-server
  - docker push federicoyre/complex-worker